import numpy as np

"""Predefined constants for the environment."""

# Observation space constants
MAX_SPEED = 100
MAX_VEH_LEN = 30
MAX_VEH_WIDTH = 15
MAX_VEH_HEIGHT = 10
MIN_REL_GOAL_COORD = -200
MAX_REL_GOAL_COORD = 200
MIN_REL_AGENT_POS = -200
MAX_REL_AGENT_POS = 200
MAX_ORIENTATION_RAD = 2 * np.pi
MAX_AGENT_COUNT = 64
MAX_PARTNER_COUNT = MAX_AGENT_COUNT - 1
# MAX_PARTNER_COUNT = 62
# Road graph constants
MIN_RG_COORD = -1000
MAX_RG_COORD = 1000
MAX_ROAD_LINE_SEGMENT_LEN = 100
MAX_ROAD_SCALE = 100
MAX_ROAD_OBS_COUNT = 64
# Feature shape constants
# EGO_FEAT_DIM = 6
EGO_FEAT_DIM = 13

PARTNER_FEAT_DIM = 9
ROAD_GRAPH_FEAT_DIM = 10
# ROAD_GRAPH_FEAT_DIM = 242
# Dataset constants
LOG_TRAJECTORY_LEN = 512

#BEV observation constants
BEV_RASTERIZATION_RESOLUTION = 200
NUM_MADRONA_ENTITY_TYPES = 11